## Security & Cost Optimization
## Use Kubernetes Secrets:
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  password: <base64_encoded_password>  # Replace with your base64-encoded password
