name: CI/CD Pipeline for Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go app
      run: go build -o myapp .

    - name: Test Go app
      run: go test ./...

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp:latest mdriyazali254362028/myapp:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push mdriyazali254362028/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up kubectl
      uses: Azure/setup-kubectl@v1
      with:
        version: v1.21.0

    - name: Deploy with Helm
      run: helm upgrade --install myapp ./helm --set image.repository=mdriyazali254362028/myapp --set image.tag=latest
